version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 009160060366.dkr.ecr.ap-south-1.amazonaws.com
      - echo Logging in to Docker Hub...
      - docker login --username "$DOCKER_HUB_USERNAME" --password "$DOCKER_HUB_PASSWORD"
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t cicdrepo .
      - docker tag cicdrepo:latest 009160060366.dkr.ecr.ap-south-1.amazonaws.com/cicdrepo:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 009160060366.dkr.ecr.ap-south-1.amazonaws.com/cicdrepo:latest

artifacts:
  files:
    - '**/*'  # Modify as necessary
