version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 009160060366.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t php-service-new .  # Updated service name
      - docker tag php-service-new:latest 009160060366.dkr.ecr.ap-south-1.amazonaws.com/cicdrepo:php-service-new  # Updated service name
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 009160060366.dkr.ecr.ap-south-1.amazonaws.com/cicdrepo:php-service-new  # Updated service name
      - echo '[{"name":"php-service-new","imageUri":"009160060366.dkr.ecr.ap-south-1.amazonaws.com/cicdrepo:php-service-new"}]' > imagedefinitions.json  # Updated service name
      - echo Creating artifact...
artifacts:
  files:
    - imagedefinitions.json
    - '**/*'  # Modify as necessary
