version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 009160060366.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t newphpapp .  # Changed to newphpapp
      - docker tag newphpapp:latest 009160060366.dkr.ecr.ap-south-1.amazonaws.com/cicdrepo:newphpapp  # Changed to newphpapp
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 009160060366.dkr.ecr.ap-south-1.amazonaws.com/cicdrepo:newphpapp  # Changed to newphpapp
      - echo '[{"name":"newphpapp","imageUri":"009160060366.dkr.ecr.ap-south-1.amazonaws.com/cicdrepo:newphpapp"}]' > imagedefinitions.json  # Changed to newphpapp
      - echo Creating artifact...
artifacts:
  files:
    - imagedefinitions.json
    - '**/*'  # Modify as necessary
